export default {
  header: {
    title: '腾讯Mac软件中心',
    subTitle: '精品软件，轻松下载',
    phoneVer: {
      url: 'http://sj.qq.com/myapp/',
      text: '手机版',
      title: '应用宝',
    },
    pcVer: {
      url: '//pc.qq.com/',
      text: 'PC版',
      title: 'PC软件中心',
    },
  },
  slider: [
    {
      zh_CN: 'QQ音乐',
      en: 'qy',
      img: '__qqy@2x-1ci_15p.png',
      download: '//dldir1.qq.com/music/clntupate/mac/QQMusicMac_Mgr.dmg',
      appStore: '//itunes.apple.com/cn/app/id595615424',
      desc: 'QQ音乐 for Mac 现已升级为6.2.0',
    },
    {
      zh_CN: 'QQ',
      en: 'qq',
      img: '__QQ@2x-2PLMfbG.png',
      download: '//dldir1.qq.com/qqfile/QQforMac/QQ_V6.5.5.dmg',
      appStore: '//itunes.apple.com/cn/app/id451108668',
      desc: 'QQ for Mac 现已升级为6.5.5',
      descStyle: { color: '#60666e' },
    },
    {
      zh_CN: '看图',
      en: 'kt',
      img: '__kantu@2x-qdh_Ho5.png',
      download: '//dldir1.qq.com/invc/tt/miniQpicview.dmg',
      appStore: '//itunes.apple.com/cn/app/id1314842898',
      desc: '看图 for Mac 现已升级为2.5.1',
    },
    {
      zh_CN: '腾讯柠檬清理',
      en: 'lemon',
      img: '__lemon@2x-1gB_nBK.png',
      download: '//pm.myapp.com/invc/xfspeed/qqpcmgr/module_update/Lemon_2.0.0.dmg',
      appStore: {
        url: '//itunes.apple.com/cn/app/id1449962996',
        style: { border: '1px solid #ddd' },
      },
      desc: '腾讯柠檬清理 for Mac 现已升级为2.0.0',
    },
    {
      zh_CN: '腾讯视频',
      en: 'qv',
      img: '__qqv@2x-aT80U9a.jpg',
      download: '//dldir1.qq.com/qqtv/mac/TencentVideo_V2.2.1.42253.dmg',
      appStore: '//itunes.apple.com/cn/app/id1231336508',
      desc: '腾讯视频 for Mac 现已升级为2.2.1',
    },
    {
      zh_CN: '富途牛牛',
      en: 'ft',
      img: '__futu@2x-jOWaggD.jpg',
      download:
        '//cdn.futunn.com/client/nn/mac/FTNNForMac_4.32.2_2018080203_std_release_std_officially.dmg',
      appStore: '//itunes.apple.com/cn/app/id664513913',
      desc: '富途牛牛 for Mac 现已升级为4.32.2',
    },
    {
      zh_CN: '截图',
      en: 'jt',
      img: '__jietu@2x-jFKJWI0.png',
      download: '//dldir1.qq.com/invc/tt/QB/Jietu/Jietu_2.2.2(11054).dmg',
      appStore: '//itunes.apple.com/cn/app/id1059334054',
      desc: '截图 for Mac 现已升级为2.3',
    },
  ],
  content: [
    {
      name: 'QQ',
      shortName: 'qq',
      img: '__qq@3x-1asJgYO.png',
      time: '2019-07-23',
      desc: '匠心之韵 · 清新聊人',
      url: '//im.qq.com/macqq/',
      download: '//dldir1.qq.com/qqfile/QQforMac/QQ_V6.5.5.dmg',
      appStore: '//itunes.apple.com/cn/app/id451108668',
    },
    {
      name: '微信',
      shortName: 'wx',
      img: '__wx@3x-lwasu0v.png',
      time: '2019-05-22',
      desc: '极致简洁 迅捷沟通',
      url: '//mac.weixin.qq.com',
      download: '//dldir1.qq.com/weixin/mac/WeChatMac.dmg',
      appStore: '//itunes.apple.com/cn/app/id836500024',
    },
    {
      name: 'QQ音乐',
      shortName: 'qy',
      img: '__qy@3x-2CNv7Gp.png',
      time: '2019-09-06',
      desc: '素美如雪，轻盈上线',
      url: '//y.qq.com/download/mac.html?part=1&amp;ADTAG=PCQQCOM',
      download: '//dldir1.qq.com/music/clntupate/mac/QQMusicMac_Mgr.dmg',
      appStore: '//itunes.apple.com/cn/app/id595615424',
    },
    {
      name: 'QQ浏览器',
      shortName: 'qb',
      img: '__qb@3x-9MmVrIR.png',
      time: '2018-11-30',
      desc: '更美的浏览器',
      url: 'http://browser.qq.com/mac/',
      download: '//dldir1.qq.com/invc/tt/QQBrowser_for_Mac.dmg',
    },
    {
      name: '腾讯视频',
      shortName: 'qv',
      img: '__qv@3x-3jYHIh8.png',
      time: '2019-02-19',
      desc: '无广告纯净播放体验',
      url: '//v.qq.com/download.html#mac',
      download: '//dldir1.qq.com/qqtv/mac/TencentVideo_V2.2.1.42253.dmg',
      appStore: '//itunes.apple.com/cn/app/id1231336508',
    },
    {
      name: '截图',
      shortName: 'jt',
      img: '__jt@3x-3_e8Lqo.png',
      time: '2018-04-27',
      desc: '轻松便捷爱截图',
      url: 'http://jietu.qq.com/',
      download: '//dldir1.qq.com/invc/tt/QB/Jietu/Jietu_2.2.2(11054).dmg',
      appStore: '//itunes.apple.com/cn/app/id1059334054',
    },
    {
      name: '看图',
      shortName: 'kt',
      img: '__kt@3x-1dfSgbf.png',
      time: '2019-06-27',
      desc: '轻松找照片',
      url: 'http://kantu.qq.com',
      download: '//dldir1.qq.com/invc/tt/miniQpicview.dmg',
      appStore: '//itunes.apple.com/cn/app/id1314842898',
    },
    {
      name: '企业微信',
      shortName: 'qywx',
      img: '__qywx@3x-cgyVIzF.png',
      time: '2019-03-11',
      desc: '让每个企业都有自己的微信',
      url: '//work.weixin.qq.com/',
      download: '//dldir1.qq.com/foxmail/work_weixin/WXWork_2.7.5.2089.dmg',
      appStore: '//itunes.apple.com/cn/app/id1189898970',
    },
    {
      name: '腾讯柠檬清理',
      shortName: 'lemon',
      img: '__lemon@3x-18MyKLd.png',
      time: '2019-06-21',
      desc: '极致清理，全新体验',
      url: '//lemon.qq.com/',
      download: '//pm.myapp.com/invc/xfspeed/qqpcmgr/module_update/Lemon_2.0.0.dmg',
      appStore: '//itunes.apple.com/cn/app/id1449962996',
    },
    {
      name: '腾讯手游助手',
      shortName: 'txsyzs',
      img: '__txsyzs@3x-3FcTnO_.png',
      time: '2019-06-25',
      desc: '电脑玩手游，腾讯唯一官方模拟器',
      url: '//syzs.qq.com/',
      download: '//dldir1.qq.com/syzs/mac/signed_TxGameAssistant_sorg68_201906211448.pkg',
    },
  ],
};
